FROM node:20-alpine

WORKDIR /app

# Install deps from lockfile
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# CRA in Docker niceties
ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
EXPOSE 3000

CMD ["npm", "run", "start"]
